[phases.setup]
# Include system packages including libmagic/file
nixPkgs = ["python311", "pip", "file"]

[phases.install]
# Install Python dependencies
cmds = ["pip install -r requirements.txt"]

[start]
# Start the application
cmd = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"